//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class uploadedProfile
    {
        public string uploadedProfileNumber { get; set; }
        public int employeeNumber { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
